# Generated by Django 3.0.6 on 2020-06-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default='', max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='contant',
            field=models.TextField(),
        ),
    ]
