# Generated by Django 3.0.6 on 2020-06-20 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200618_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contant',
            new_name='content',
        ),
    ]
